// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaedH1ueUCKrspAMZjEvYGUagZgzivIFU',
    appId: '1:677460898065:web:967002e617976b8a8adcb0',
    messagingSenderId: '677460898065',
    projectId: 'authentic-ulang',
    authDomain: 'authentic-ulang.firebaseapp.com',
    storageBucket: 'authentic-ulang.firebasestorage.app',
    measurementId: 'G-9DMQPSDTG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8l78jQriET_m1iiNOWTAR7oIgnBpIcZQ',
    appId: '1:677460898065:android:406bb5651cb35a3c8adcb0',
    messagingSenderId: '677460898065',
    projectId: 'authentic-ulang',
    storageBucket: 'authentic-ulang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpjseeeWaXFfDfnNTwcvJqrdfY2h9tKsI',
    appId: '1:677460898065:ios:694d6b6d95741c378adcb0',
    messagingSenderId: '677460898065',
    projectId: 'authentic-ulang',
    storageBucket: 'authentic-ulang.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
